apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: hynetimberpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hynetimberpipelinesjavascriptdocker 
    spec:
      containers:
        - name: hynetimberpipelinesjavascriptdocker 
          image: hynecontainerregistry.azurecr.io/hynetimberpipelinesjavascriptdocker
          ports:
          - containerPort: 8080